baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Eric vlog"

# Change the default theme to be use when building the site with Hugo
theme = "FixIt"

[params]
  # FixIt theme version
  version = "0.2.X"
  description = "Eric blog"
  # site keywords
  keywords = ["Eric", "vlog"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # FixIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # FixIt NEW | 0.2.0 date format
  dateFormat = "02-01-2006"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]
  # FixIt NEW | 0.2.12 enable PWA
  enablePWA = true
  # FixIt NEW | 0.2.14 whether to add external Icon for external links automatically
  externalIcon = false
  # FixIt NEW | 0.2.14 FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
  # You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
  disableThemeInject = false
  
[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  # FixIt NEW | 0.2.0 App icon config
  title = "Eric vlog"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
  # FixIt CHANGED | 0.2.12 Android browser theme color
  [params.app.themeColor]
    light = "#ffffff"
    dark = "#252627"
	
# FixIt NEW | 0.2.0 Search config
[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # FixIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # FixIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # FixIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # FixIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = true
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""	
	
# Header config
[params.header]
  # desktop header mode ("sticky", "normal", "auto")
  desktopMode = "sticky"
  # mobile header mode ("sticky", "normal", "auto")
  mobileMode = "auto"
  # FixIt NEW | 0.2.0 Header title config
  [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "ωєℓ¢σмє тσ му вℓσg"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # FixIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
	
# Footer config
[params.footer]
  enable = true
  # FixIt NEW | 0.2.0 Custom content (HTML format is supported)
  custom = ''
  # FixIt NEW | 0.2.0 whether to show Hugo and theme info
  hugo = true
  # FixIt NEW | 0.2.0 whether to show copyright info
  copyright = true
  # FixIt NEW | 0.2.0 whether to show the author
  author = true
  # Site creation year
  since = 2019
  # FixIt NEW | 0.2.14 Site creation time
  siteTime = '' # e.g. '2019-02-03T19:30:34+08:00'
  # FixIt NEW | 0.2.14 whether to show total word count of site content
  wordCount = true
  # ICP info only in China (HTML format is supported)
  icp = ""
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# FixIt NEW | 0.2.0 Section (all posts) page config
[params.section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "02-01"
  # amount of RSS pages
  rss = 10
  # FixIt NEW | 0.2.13 recently updated posts settings
  [params.section.recentlyUpdated]
    enable = true
    rss = true
    days = 30
    maxCount = 10
	
# FixIt NEW | 0.2.0 List (category or tag) page config
[params.list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "02-01"
  # amount of RSS pages
  rss = 10
  
# Home page config
[params.home]
  # FixIt NEW | 0.2.0 amount of RSS pages
  rss = 10
  # Home page profile
  [params.home.profile]
    enable = true
    # FixIt NEW | 0.2.13 Gravatar mirror site domain, default: "www.gravatar.com"
    # FixIt CHANGED | 0.2.14 FixIt DELETED | 0.2.15 The parameter `home.profile.gravatarSite` is deprecated since v0.2.14, use `gravatar.host` instead
    # gravatarSite = ""
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # FixIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = "░E░r░i░c░ ░V░l░o░g░"
    # subtitle shown in home page
    subtitle = "(っ◔◡◔)っ 🐬🐬♥ Record bits and pieces, and other messy things.♥"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # FixIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [params.home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6  
	
	
# Social config about the author
[params.social]
  GitHub = "ericvlog"
  Linkedin = ""
  Twitter = ""
  Instagram = ""
  Facebook = "plshareme"
  Telegram = "plsharevme"
  Medium = ""
  Gitlab = ""
  Youtubelegacy = ""
  Youtubecustom = ""
  Youtubechannel = ""
  Tumblr = ""
  Quora = ""
  Keybase = ""
  Pinterest = ""
  Reddit = ""
  Codepen = ""
  FreeCodeCamp = ""
  Bitbucket = ""
  Stackoverflow = ""
  Weibo = ""
  Odnoklassniki = ""
  VK = ""
  Flickr = ""
  Xing = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Bandcamp = ""
  Paypal = ""
  Fivehundredpx = ""
  Mix = ""
  Goodreads = ""
  Lastfm = ""
  Foursquare = ""
  Hackernews = ""
  Kickstarter = ""
  Patreon = ""
  Steam = ""
  Twitch = ""
  Strava = ""
  Skype = ""
  Whatsapp = "60133724443"
  Zhihu = ""
  Douban = ""
  Angellist = ""
  Slidershare = ""
  Jsfiddle = ""
  Deviantart = ""
  Behance = ""
  Dribbble = ""
  Wordpress = ""
  Vine = ""
  Googlescholar = ""
  Researchgate = ""
  Mastodon = ""
  Thingiverse = ""
  Devto = ""
  Gitea = ""
  XMPP = ""
  Matrix = ""
  Bilibili = ""
  # ORCID, ... , CSDN FixIt NEW | 0.2.13
  ORCID = ""
  Liberapay = ""
  Ko-Fi = ""
  BuyMeaCoffee = ""
  Linktree = ""
  QQ = ""
  QQGroup = ""
  Diaspora = ""
  CSDN = ""
  Email = "plsharevme@gmail.com"
  RSS = true # FixIt NEW | 0.2.0

# FixIt CHANGED | 0.2.0 Page config
[params.page]
  # FixIt NEW | 0.2.0 whether to hide a page from home page
  hiddenFromHomePage = false
  # FixIt NEW | 0.2.0 whether to hide a page from search results
  hiddenFromSearch = false
  # FixIt NEW | 0.2.0 whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = false
  # FixIt NEW | 0.2.0 whether to enable the ruby extended syntax
  ruby = true
  # FixIt NEW | 0.2.0 whether to enable the fraction extended syntax
  fraction = true
  # FixIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
  fontawesome = true
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = true
  # FixIt NEW | 0.2.4 whether to show the full text content in RSS
  rssFullText = false
  # FixIt NEW | 0.2.13 Page style ("narrow", "normal", "wide", ...)
  pageStyle = "normal"
  # FixIt NEW | 0.2.14 Gravatar is force-used as the author's avatar
  gravatarForce = false
  # FixIt NEW | 0.2.0 Table of the contents config
  [params.page.toc]
    # whether to enable the table of the contents
    enable = true
    # FixIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
    # FixIt NEW | 0.2.13 position of TOC ("left", "right")
    position = "right"
  # FixIt NEW | 0.2.13 Display a message at the beginning of an article to warn the reader that its content might be expired
  [params.page.expirationReminder]
    enable = false
    # Display the reminder if the last modified time is more than 90 days ago
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago
    warning = 180
    # If the article expires, close the comment or not
    closeComment = false
  # FixIt CHANGED | 0.2.0 KaTeX mathematical formulas (https://katex.org)
  [params.page.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # FixIt NEW | 0.2.0 Code config
  [params.page.code]
    # whether to show the copy button of the code block
    copy = true
    # FixIt NEW | 0.2.13 whether to show the edit button of the code block
    edit = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 10
  # FixIt NEW | 0.2.14 Post edit
  [params.page.edit]
    enable = false
    # url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # Link for fork & edit
    url = "" # Link for fork & edit
  # FixIt NEW | 0.2.0 Mapbox GL JS config (https://docs.mapbox.com/mapbox-gl-js)
  [params.page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v9"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v9"
    # whether to add NavigationControl
    navigation = true
    # whether to add GeolocateControl
    geolocate = true
    # whether to add ScaleControl
    scale = true
    # whether to add FullscreenControl
    fullscreen = true
  # FixIt CHANGED | 0.2.0 social share links in post page
  [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = true
    Pinterest = true
    Tumblr = true
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = true
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = true
    Renren = false
    Myspace = true
    Blogger = true
    Baidu = false
    Odnoklassniki = false
    Evernote = true
    Skype = false
    Trello = false
    Mix = false
  # FixIt CHANGED | 0.2.13 Comment config
  [params.page.comment]
    enable = true
    # FixIt NEW | 0.2.13 Artalk comment config (https://artalk.js.org/)
    [params.page.comment.artalk]
      enable = false
      server = "https://localhost/api/"
      site = "默认站点"
      placeholder = ""
      noComment = ""
      sendBtn = ""
      editorTravel = true
      flatMode = 'auto'
      maxNesting = 3
      # It take effect when `params.page.lightgallery` is enabled
      lightgallery = false
    # Disqus comment config (https://disqus.com)
    [params.page.comment.disqus]
      # FixIt NEW | 0.1.1
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "ericvlog"
    # Gitalk comment config (https://github.com/gitalk/gitalk)
    [params.page.comment.gitalk]
      # FixIt NEW | 0.1.1
      enable = false
      owner = "ericvlog"
      repo = "ericvlog.github.io"
      clientId = "fe7d1c43ea639f51852c"
      clientSecret = "e7a824e54df13f340cd540bc8b4df4ecc8b76d1e"
    # Valine comment config (https://github.com/xCss/Valine)
    [params.page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta= ""
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""
      # FixIt NEW | 0.2.6 emoji data file name, default is "google.yml"
      # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
      # located in "themes/FixIt/assets/data/emoji/" directory
      # you can store your own data files in the same path under your project:
      # "assets/data/emoji/"
      emoji = ""
      commentCount = true # FixIt NEW | 0.2.13
    # FixIt NEW | 0.2.13 Waline comment config (https://waline.js.org)
    [params.page.comment.waline]
      enable = false
      serverURL = ""
      visitor = false
      emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
      meta = ['nick', 'mail', 'link']
      requiredMeta = []
      login = 'enable'
      wordLimit = 0
      pageSize = 10
      uploadImage = true
      highlight = true
      mathTagSupport = false
      commentCount = true
    # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""
    # FixIt NEW | 0.2.0 Telegram comments config (https://comments.app)
    [params.page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
    # FixIt NEW | 0.2.0 Commento comment config (https://commento.io)
    [params.page.comment.commento]
      enable = false
    # FixIt NEW | 0.2.5 Utterances comment config (https://utteranc.es)
    [params.page.comment.utterances]
      enable = false
      # owner/repo
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # FixIt NEW | 0.2.13 Twikoo comment config (https://twikoo.js.org/)
    [params.page.comment.twikoo]
      enable = false
      envId = ""
      region = ""
      path = ""
      visitor = true
      commentCount = true
      # It take effect when `params.page.lightgallery` is enabled
      lightgallery = false
    # FixIt NEW | 0.2.14 Giscus comments config
    [params.page.comment.giscus]
      enable = false
      repo = ""
      repoId = ""
      category = ""
      categoryId = ""
      mapping = ""
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom" # top, bottom
      lightTheme = "light"
      darkTheme = "dark"
      lazyLoad = true
  # FixIt NEW | 0.2.7 Third-party library config
  [params.page.library]
    [params.page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      # someCSS = "https://cdn.example.com/some.css"
    [params.page.library.js]
      # someJavascript = "some.js"
      # located in "assets/"
      # Or
      # someJavascript = "https://cdn.example.com/some.js"
  # FixIt CHANGED | 0.2.10 Page SEO config
  [params.page.seo]
    # image URL
    images = []
    # Publisher info
    [params.page.seo.publisher]
      name = ""
      logoUrl = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/Lruihao/FixIt/issues/43)
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	


